const constants = {

    CHANGE_ADDING_STATE: "CHANGE_ADDING_STATE",

    HIDE_SHOW_FILTERS: "HIDE_SHOW_FILTERS",
    FILTERS_DROPPED: "FILTERS_DROPPED",
    FILTER_CHANGED: "FILTER_CHANGED",

    DRAG_CHANGE_PRIORITY_NOTE: "DRAG_CHANGE_PRIORITY_NOTE",
    SET_INITIAL_NOTES_STATE: "SET_INITIAL_NOTES_STATE",
    REMOVE_NOTE: "REMOVE_NOTE",
    UPDATE_NOTE: "UPDATE_NOTE",
    EDIT_NOTE: "EDIT_NOTE",
    DRAG_NOTE: "DRAG_NOTE",
    ADD_NOTE: "ADD_NOTE",

    CONTENT_SEARCH_FILTER: "content-search",
    PRIORITY_SEARCH_FILTER: "priority-search",
    DATE_FROM_SEARCH: "date-from-search",
    DATE_TO_SEARCH: "date-to-search"
};

export {constants}